### ISSUE TITLE
 mushroom-rl :from mushroom_rl.algorithms.actor_critic import SAC, DDPG, SAC_hybrid, LRL, PPO

### ISSUE THREAD

**Issue by DevilCJS89** [Lakshadeep/pre-grasp-approaching#7]
# Great job, I'm learning this project, but I've encountered some problems. 
## error-1:
python train/base_motion.py   
```
30/05/2024 20:44:38 [INFO] Epoch 145 | J: 565972.6342289235 R: 1341967.7419354839 entropy: -0.11714837700128555                                          
30/05/2024 20:46:59 [INFO] Epoch 146 | J: 531177.9096545189 R: 1293333.3333333333 entropy: -0.18445532023906708                                          
30/05/2024 20:49:17 [INFO] Epoch 147 | J: 612790.9743068021 R: 1441666.6666666667 entropy: -0.24634452164173126                                          
30/05/2024 20:51:29 [INFO] Epoch 148 | J: 601981.0250052711 R: 1418333.3333333333 entropy: -0.26264601945877075                                          
30/05/2024 20:53:49 [INFO] Epoch 149 | J: 535623.6501714567 R: 1293333.3333333333 entropy: -0.20987452566623688                                          
30/05/2024 20:56:11 [INFO] Epoch 150 | J: 511678.3084094932 R: 1253333.3333333333 entropy: -0.19732102751731873                                          
Training done                                                                                                                                            
Error executing job with overrides: []
Traceback (most recent call last):
  File "train/base_motion.py", line 147, in main
    experiment(cfg, alg=SAC)
  File "train/base_motion.py", line 140, in experiment
    mdp.shutdown()
AttributeError: 'BaseMotion' object has no attribute 'shutdown'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
ERROR: Python exiting while SimulationApp was still running, Please call close() on the SimulationApp object to exit cleanly
```

## error-2
python train/grasp_decision.py              line15
from mushroom_rl.algorithms.actor_critic import SAC, DDPG, SAC_hybrid, LRL, PPO
it seems no " SAC_hybrid, LRL "
Did something change for mushroom-rl==1.7.2 ?
```
Traceback (most recent call last):
  File "train/grasp_decision.py", line 15, in <module>
    from mushroom_rl.algorithms.actor_critic import SAC, DDPG, LRL, PPO
ImportError: cannot import name 'LRL' from 'mushroom_rl.algorithms.actor_critic' (/home/cjs/isaacsim/isaac_sim/pre-grasp-approaching/mushroom-rl/mushroom_rl/algorithms/actor_critic/__init__.py)
```

```
Traceback (most recent call last):
  File "train/grasp_decision.py", line 20, in <module>
    from pre_grasp_approaching.tasks.grasp_decision import GraspDecision
  File "/home/cjs/isaacsim/isaac_sim/pre-grasp-approaching/pre_grasp_approaching/tasks/grasp_decision.py", line 1, in <module>
    from motion_planning.tasks.task import Task
ModuleNotFoundError: No module named 'motion_planning'
```

**Comment by Lakshadeep** [comment]
Thank you for posting the errors. I have now pushed some fixes. I have also pushed the Layered RL file, which must be installed inside the mushroom_rl repository. Please take a look at the 'algorithms' folder in the repo for details. Unfortunately, I don't have the setup at present to test the code. If you find/fix any bugs, you can create a pull request.

**Comment by Lakshadeep** [comment]
Error-1 can be ignored.
