### ISSUE TITLE
Thank you very much for your response.

### ISSUE THREAD

**Issue by DevilCJS89** [Lakshadeep/pre-grasp-approaching#9]
Thank you very much.
```
Logging in folder: /home/cjs/isaacsim/isaac_sim/pre-grasp-approaching/Planning/Data/PGA/2/SAC
02/06/2024 22:27:59 [INFO] ###################################################################################################
02/06/2024 22:27:59 [INFO] Experiment Algorithm: SAC
2024-06-02 14:28:00 [10,312ms] [Warning] [omni.physicsschema.plugin] ScaleOrientation is not supported for rigid bodies, prim path: /World/Cylinder. You may ignore this if the scale is close to uniform.
2024-06-02 14:28:00 [10,354ms] [Warning] [omni.physicsschema.plugin] ScaleOrientation is not supported for rigid bodies, prim path: /World/BaseTop. You may ignore this if the scale is close to uniform.
2024-06-02 14:28:22 [32,336ms] [Warning] [omni.physx.plugin] The rigid body at /World/ur5e/base has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass, small sphere approximated inertia was used. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for. If you do not want the objects to collide, add colliders regardless then disable the 'enable collision' property.
2024-06-02 14:28:22 [32,336ms] [Warning] [omni.physx.plugin] The rigid body at /World/ur5e/tool0 has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass, small sphere approximated inertia was used. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for. If you do not want the objects to collide, add colliders regardless then disable the 'enable collision' property.
2024-06-02 14:28:22 [32,336ms] [Warning] [omni.physx.plugin] The rigid body at /World/ur5e/world has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass, small sphere approximated inertia was used. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for. If you do not want the objects to collide, add colliders regardless then disable the 'enable collision' property.
Simulation start status:  True
MDP observation space low: [-3 -3 -3 -1 -1 -1 -1]
MDP observation space high: [3 3 3 1 1 1 1]
Error executing job with overrides: []
Traceback (most recent call last):
  File "train/grasp_decision.py", line 151, in main
    experiment(cfg, alg=SAC)
  File "train/grasp_decision.py", line 62, in experiment
    output_shape=action_space_discrete,
NameError: name 'action_space_discrete' is not defined

```
It seems like 'action_space_discrete' is not defined.

What's more, please help me take a look at my previous issue.
Thank you!
Can I submit a pr for my job.

**Comment by DevilCJS89** [comment]
I have studied the relevant papers and materials, and I am  learning the code , but I have some problems that seem to be caused by missing parts of this code . I am looking forward to seeing your complete working code.
